# SwiftLint Configuration for Context App

# Rules to disable (these tend to be overly strict for most projects)
disabled_rules:
  - trailing_whitespace

# Rules to enable (these help catch common issues)
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - contains_over_first_not_nil

# Analyzer rules (run with 'swiftlint analyze')
analyzer_rules:
  - unused_import
  - unused_declaration

# Directories to include in linting
included:
  - context
  - contextTests
  - contextUITests

# Directories to exclude from linting
excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - .swiftpm

# Custom rule configurations
line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

# Identifier naming rules
identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

# Type naming rules
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 50

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 15

# Nesting levels
nesting:
  type_level:
    warning: 2
    error: 3 