name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  XCODE_VERSION: '15.4'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app
    
    - name: Show build environment
      run: |
        echo "macOS version:"
        sw_vers
        echo "Xcode version:"
        xcodebuild -version
        echo "Swift version:"
        swift --version
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Resolve dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
          -project context.xcodeproj \
          -scheme context
    
    - name: Build
      run: |
        xcodebuild build-for-testing \
          -project context.xcodeproj \
          -scheme context \
          -destination 'platform=macOS' \
          -configuration Debug \
          -derivedDataPath DerivedData
    
    - name: Run all tests with coverage
      run: |
        xcodebuild test \
          -project context.xcodeproj \
          -scheme context \
          -destination 'platform=macOS' \
          -configuration Debug \
          -derivedDataPath DerivedData \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults.xcresult \
          | xcpretty --report junit --output test-results.xml
      continue-on-error: true
    
    - name: Generate coverage report
      run: |
        xcrun xcresulttool get --format json \
          --path TestResults.xcresult > test-results.json
        
        # Extract coverage percentage
        xcrun xccov view --report --json TestResults.xcresult > coverage.json
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          TestResults.xcresult
          test-results.xml
          test-results.json
          coverage.json
        retention-days: 30
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: test-results.xml
        reporter: java-junit
    
    - name: Comment PR with test results
      uses: kishikawakatsumi/xcresulttool@v1
      if: github.event_name == 'pull_request' && always()
      with:
        path: TestResults.xcresult
        show-code-coverage: true
        
  lint:
    name: SwiftLint
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      continue-on-error: true 