name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install dependencies
        run: nix develop --command pnpm install

      - name: Run linter
        run: nix develop --command pnpm lint

      - name: Check formatting
        run: nix develop --command pnpm format --check

      - name: Build application
        run: nix develop --command pnpm build

      - name: Test packaging (without publishing)
        run: |
          nix develop --command bash -c "
            # Just test that packaging works, don't upload
            pnpm package --dir --publish never
          "
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 